# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Matheus Moreira/Documents/UnB/SD 2/experimento02/experimento02.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Matheus Moreira/Documents/UnB/SD 2/experimento02/experimento02.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Matheus Moreira/Documents/UnB/SD 2/experimento02/experimento02.srcs/sources_1/new/wCount.vhd}
  {C:/Users/Matheus Moreira/Documents/UnB/SD 2/experimento02/experimento02.srcs/sources_1/new/somador2.vhd}
  {C:/Users/Matheus Moreira/Documents/UnB/SD 2/experimento02/experimento02.srcs/sources_1/new/somador1.vhd}
  {C:/Users/Matheus Moreira/Documents/UnB/SD 2/experimento02/experimento02.srcs/sources_1/new/r_time.vhd}
  {C:/Users/Matheus Moreira/Documents/UnB/SD 2/experimento02/experimento02.srcs/sources_1/new/rCount.vhd}
  {C:/Users/Matheus Moreira/Documents/UnB/SD 2/experimento02/experimento02.srcs/sources_1/new/comp2.vhd}
  {C:/Users/Matheus Moreira/Documents/UnB/SD 2/experimento02/experimento02.srcs/sources_1/new/comp1.vhd}
  {C:/Users/Matheus Moreira/Documents/UnB/SD 2/experimento02/experimento02.srcs/sources_1/new/FSM.vhd}
  {C:/Users/Matheus Moreira/Documents/UnB/SD 2/experimento02/experimento02.srcs/sources_1/new/bloco_operacional.vhd}
  {C:/Users/Matheus Moreira/Documents/UnB/SD 2/experimento02/experimento02.srcs/sources_1/new/Top_level.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Matheus Moreira/Documents/UnB/SD 2/VHDL/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Matheus Moreira/Documents/UnB/SD 2/VHDL/Basys3_Master.xdc}}]


synth_design -top Top_level -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Top_level.dcp

catch { report_utilization -file Top_level_utilization_synth.rpt -pb Top_level_utilization_synth.pb }
